export enum ERROR_CODE {
  NOT_FOUND = 'NOT_FOUND',
  ACCOUNT_NOT_ACTIVATED = 'ACCOUNT_NOT_ACTIVATED',
  BLOCK_ACCOUNT = 'BLOCK_ACCOUNT',
  REQUEST_CHANGE_PASSWORD = 'REQUEST_CHANGE_PASSWORD',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  EMAIL_EXISTED = 'EMAIL_EXISTED',
  OLD_PASSWORD_NOT_MATCH = 'OLD_PASSWORD_NOT_MATCH',
  OLD_PASSWORD_SAME_NEW_PASSWORD = 'OLD_PASSWORD_SAME_NEW_PASSWORD',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_DOES_NOT_WORK = 'EMAIL_DOES_NOT_WORK',
  TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  LABEL_EXISTED = 'LABEL_EXISTED',
  UPLOAD_ERROR = 'UPLOAD_ERROR',
  USERNAME_PASSWORD_NOT_MATCH = 'USERNAME_PASSWORD_NOT_MATCH',
  EMAIL_DOES_NOT_EXISTED = 'EMAIL_DOES_NOT_EXISTED',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',
  SUBMIT_REPORT_FAILED = 'SUBMIT_REPORT_FAILED',
  DOWNLOAD_DOCUMENT_FAILED = 'DOWNLOAD_DOCUMENT_FAILED',
}

export enum UserRole {
  Admin = 1,
  Approver = 2,
  Uploader = 3,
}

export const HIGHLIGHT_OFFSET_DAY_CELL_STYLING = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFFF0000' },
};

export const TIMECARD_COLUMN_RANGES = [
  '0',
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
];

export const IMPORT_COLUMN_RANGES = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
];
